"""init database railway

Revision ID: 2e0918c13901
Revises: 975572c65fc3
Create Date: 2025-05-01 18:52:53.919050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e0918c13901'
down_revision = '975572c65fc3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'total',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('pedidos', 'estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('pedidos', 'fecha_pedido',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_pedidos_usuario_id_usuario'), 'pedidos', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('producto', 'nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('producto', 'marca',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('producto', 'precio',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('producto', 'categoria',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('usuario', 'nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('usuario', 'telefono',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'telefono',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('usuario', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('producto', 'categoria',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('producto', 'precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=False)
    op.alter_column('producto', 'marca',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('producto', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_pedidos_usuario_id_usuario'), 'pedidos', type_='foreignkey')
    op.alter_column('pedidos', 'fecha_pedido',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('pedidos', 'estado',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.MONEY(),
               nullable=True)
    # ### end Alembic commands ###
