"""init

Revision ID: 4dda5117f9bd
Revises: 088a5655c8e6
Create Date: 2025-04-07 17:13:02.789371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dda5117f9bd'
down_revision = '088a5655c8e6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuario_email_key', 'usuario', type_='unique')
    op.create_unique_constraint(op.f('uq_usuario_email'), 'usuario', ['email'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_usuario_email'), 'usuario', type_='unique')
    op.create_unique_constraint('usuario_email_key', 'usuario', ['email'])
    # ### end Alembic commands ###
