"""init database render

Revision ID: 975572c65fc3
Revises: 369b49511c48
Create Date: 2025-05-01 17:50:43.400337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975572c65fc3'
down_revision = '369b49511c48'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
