"""init db render

Revision ID: 913f0cc46b22
Revises: 2e0918c13901
Create Date: 2025-05-01 20:50:45.666983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913f0cc46b22'
down_revision = '2e0918c13901'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
