"""Add detallePedido table

Revision ID: 5a0d7fb82dc2
Revises: 4dda5117f9bd
Create Date: 2025-04-08 17:05:52.762175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0d7fb82dc2'
down_revision = '4dda5117f9bd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detallePedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('fk_detallePedido_pedido_id_pedidos'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_detallePedido_producto_id_producto'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detallePedido'))
    )
    op.drop_table('detallepedido')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detallepedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name='fk_pedido', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name='fk_producto', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='detallepedido_pkey')
    )
    op.drop_table('detallePedido')
    # ### end Alembic commands ###
