"""Add detallePedido table up

Revision ID: 369b49511c48
Revises: 5a0d7fb82dc2
Create Date: 2025-04-08 18:38:33.078321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369b49511c48'
down_revision = '5a0d7fb82dc2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
